# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cosmos33/MMSpecs.git'

# platform :ios, '9.0'

target 'ZAMoMoSDKTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for ZAMoMoSDKTest
  pod 'ZALiveModule', :path => '../'
  pod 'ZAMoMoRender', :path => '../'
  pod 'MMBeautyKit', '=2.5.4-interact'
  pod 'MetalPetal/Static', '1.13.0', :modular_headers => true
end
